name: Test & Publish release

on: push

jobs:
  build:
    name: BUILD TEST DEPLOY
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Git config
        run: |
           git config user.name github-actions
           git config user.email github-actions@github.com           

      - name: Install dependencies
        run: pnpm install
        
      - name: Run Unit Tests
        run: npm run test
        
      - name: Build Docs & Compile to JS
        run: npm run build
      
      - name: Commit changes
        run: |
            git add .
            git commit -am ':memo: Generated docs'


      - name: Git config
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

      - name: Release to GitHubh
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
           generate_release_notes: true

      - name: Publish to NPM
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish
        env:
             NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}         

      - name: Push version change back to origin
        if: success()
        run: git push origin HEAD
